name: Picture My World
highlighter: rouge
url: http://picturemy.world/
#url: http://127.0.0.1:4000/

author:
  name: Kevin Delord

# Site settings
# title:                Picture My World
# email:                delord.kevin@gmail.com
# author:               Kevin Delord

# Build settings
markdown:     kramdown
sass:
  compressed: true

paginate:     10

# https://github.com/jekyll/jekyll/issues/2938
exclude: [vendor]

gems:
  - jekyll-sitemap
  - jekyll-paginate

maps:
  google:
    api_key: AIzaSyD8L1sSjFveHxHM_3wxw73olaklHZukfrU

collections:
  videos:

content:
  recent_limit: 15
